// Copy the repo-root catalog manifest into public/ so the built site can fetch
// it at ${BASE_URL}index.json (Pages serves public/* at the site root). Run in
// predev + prebuild. index.json is generated by scripts/build_index.py.
import { copyFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../index.json");
const dest = resolve(here, "../public/index.json");

await mkdir(dirname(dest), { recursive: true });
await copyFile(src, dest);
console.log(`copied ${src} -> ${dest}`);
